export const calendarData = [
    { date: 1, status: "late", details: "5MIN" },
    { date: 2, status: "present" },
    { date: 3, status: "present" },
    { date: 4, status: "present" },
    { date: 5, status: "present" },
    { date: 6, status: "present" },
    { date: 7, status: "absent" },
    { date: 8, status: "present" },
    { date: 9, status: "present" },
    { date: 10, status: "present" },
    { date: 11, status: "present" },
    { date: 12, status: "present" },
    { date: 13, status: "present" },
    { date: 14, status: "present" },
    { date: 15, status: "present" },
    { date: 16, status: "present" },
    { date: 17, status: "present" },
    { date: 18, status: "absent" },
    { date: 19, status: "present" },
    { date: 20, status: "present" },
    { date: 21, status: "present" },
    { date: 22, status: "present", current: true },
    { date: 23, status: "present" },
    { date: 24, status: "present" },
    { date: 25, status: "present" },
    { date: 26, status: "present" },
    { date: 27, status: "present" },
    { date: 28, status: "present" },
    { date: 29, status: "present" },
    { date: 30, status: "present" },
    { date: 31, status: "present" },
  ];
  